baseurl = "https://th-koeln.github.io/mi-website-2018/"
title = "Medieninformatik an der TH KÃ¶ln"
theme = "micgn"
languageCode = "de-de"
sectionPagesMenu = "main"
publishDir = "docs"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  baseFragment = "/mi-website-2018"
  template = ""

[taxonomies]
  tag = "tags"
  category = "categories"
  year = "years"
  paper = "papers"
  keyword = "keywords"
  betreuer = "betreuer"
  autor = "autoren"
  modul = "module"

[outputs]
  page = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
  home = ["html", "JSON"]