name: Deploy on prod
on:
  push:
    branches: ["master"]
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
#      - name: ðŸ›’ Checkout
#        uses: actions/checkout@v2
#
#      - name: âœ¨ Setup Hugo
#        env:
#          HUGO_VERSION: 0.111.3
#        run: |
#          mkdir ~/hugo
#          cd ~/hugo
#          curl -L "https://github.com/gohugoio/hugo/releases/download/v0.107.0/hugo_extended_0.107.0_Linux-64bit.tar.gz" --output hugo.tar.gz
#          tar -xvzf hugo.tar.gz
#          sudo mv hugo /usr/local/bin
#
#      - name: ðŸ› ï¸ Build
#        run: hugo --source . --minify
#
#      - name: ðŸ”‘ Install SSH Key
#        run: |
#          install -m 600 -D /dev/null ~/.ssh/id_rsa
#          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
#          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: ðŸš€ Deploy
        uses: appleboy/ssh-action@master
        with:
          script: |
             mkdir '/usr/home/mi-labor/public_html_2/'
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          

#            rsync -avz --delete -e 'ssh' 'public/' '/usr/home/mi-labor/public_html_2/'
